doc.type.html
script
filename=covidstrings26background.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button (change color)
public fun with graphics(){
jpanel color panel=new j panel();
this add (panel,center )
JPanel Button Panel=
New J Panel (Flowlayout.Center)
ButtonPanel.Add(RandomButton);
Random.Button Add ActionListener(New Action Listener()
Override 
Public ActionPerformed(ActionEvent E)
Random R= NewRandom();
ColorPanel.SetBackground(New Color (RNextInt(13),)(RNextInt(13),)(RNextInt(13),)(RNextInt(13),)(RNextInt(13),)(RNextInt(13),)(RNextInt(13),)(RNextInt(13),(RNextInt(13),(RNextInt(13),(RNextInt(13),(RNextInt(13),(RNextInt(13)))
ButtonPanel.Add(OptionButton);
OptionButton.Add ActionListener(New Action Listener()
Override 
Public ActionPerformed(ActionEvent E)
Color M=JColorChooser.ShowDialog(FunWithGraphics.This,)
If(Multi!=Null)
Color Panel Set.Background(Multi)
This.Add(ButtonPanel, BorderLayout.South)
Public Static Main(String [] Args)
JFrame F =New Covid Strings26()
F.Set Title(Covid Strings26)
F.Set Default CloseOperation(JFrame. Exit_On_Close);
F.SetSize
F.Set Visible(True);
<Label Id=LblScore>Zero</Label>
Var Score=Zero
If (Mult ==X*Y)
[Non-Concatenated]
Score+=Ten
Else:
Score-=Ten
If (Mult ==X*Y)
[Concatenated]
Score+=Twenty
Else:
Score-=Twenty
LblScore= Document.GetElementbyId(LblScore)
Lbl.Score.InnerHTML=Score
Public ActionPerformed(Action Event E) 
System.Out Print.In (Next Button Clicked)
Frame.Add(Next Button);
Frame Set Visible True
Object {A:One,B:Two,C:Three,D:Four,E:Five, F:Six, G:Seven, H:Eight}
Keys Object Keys(Team)
Entries Object Entries(Obj);
Value Object= [Team Color]
return filename
