doc.type.html
script
filename=covid strings26.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=documentgetelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new  button (change color)
public fun with graphics(){
color panel=new j panel();
add(panel,center )
button panel
new panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
num teams
total players= players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args)
jframe f =new covid strings26()
f.set title(covid strings26)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lbl score)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in(next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object=[team color]
covid strings team list26=[orange rna messengers ,yellow moxie ,pink covid disease fighters ,teal terminators ,red protein spikers,purple brave hearts,indigo isos,violet brave hearts]
covid strings multiple choice list26=[1:a rapists b doomscrollers c felons d your crazy uncle,2:a treat b cure c diagnose d spot,3:a triple b double c single d quadruple,4:a personal b domestic c geopolitical d holiday,5:a from the jeffersons b trump c from coyote ugly d from all in the family,6:a zigzagging b assassinating donald trump c falling for dating scams d censorship,7:a shedding b high jumping c hurdling d skepticism,8:a time when the sun becomes a red giant b future c time the dinosaurs went extinct d second biden administration,9:a train b air c thanksgiving d car,10:a mars b io c titan d humans,11:a4502 b2749 c2035 d2020,12:a twisters b landslides c wars d capture the flag games,13:a seat belt laws b testing c reports on maga dissenters d polling,14:a department of health and human services b general services administration  c pentagon d state department,15:a seat belt laws b testing c reports on maga dissenters d polling,16:a enzyme b abzymes c protein d sweet16]
covid strings phrase list26=[non-concatenated strings "vaccine shedding is one thing you should not expect after getting vaccinated"
"people who talk about zoonotic viruses causing pandemics are probably not murders or felons"
"when it comes to air travel dont knowingly be infectious,not follow covid restrictions or a risk for spreading disease"
"nanoparticles though can target multiple variants through the spike protein"
"covid beginning in2020 is one reason why its weird to ask were you better off4 years ago"
"one example is that melania trump literally said youre blowing this"
"another example involves the fact that lockdowns didnt do much to prevent spread"
"trump saying slow the testing down didnt help either"
concatenated strings
"even"+"so"+"mistakes"+"are"+"not"+"necessarily"+"proof"+"of"+"covid"+"censorship"
"long"+"covid"+"will"+"not"+"be"+"as"+"much"+"of"+"a"+"problem"+"in"+"the"+"future"
"ai"+"can"+"also"+"help"+"diagnose"+"covid"+"cases"+"in"+"the"+"future"+"too"
"it"+"might"+"even"+"know"+"that"+"being"+"double"+"jointed"+"increases"+"your"+"risk"+"of"+"long"+"covid"
"on"+"a"+"geopolitical"+"level"+"the"+"book"+"biohacked"+"can"+"talk"+"about"+"the"+"future"+"of"+"chinise"+"pandemic"+"bioweapons"
"it"+"is"+"also"+"important"+"to"+"note"+"that"+"the"+"next"+"pandemic"+"might"+"come"+"from"+"humans"
"perhaps"+"it"+"could"+"be"+"a"+"bioweapon"+"that"+"could"+"be"+"deployed"+"in"+"a"+"future"+"war"
"even"+"the"+"pentagon"+"has"+"issued"+"a"+"warning"+"over"+"this"+"scenario"]
covid strings math problems list26=[ non-concatenated "if a line showed that there was a straight line on the effect of covid and lockdowns what relationship exists"?,"if the slope of the covid-lockdowns line is 1/2 and the y intercept is2 what would the y coordinate be if the x coordinate is7"?,"if the point (7,5.5) was reflected across the x axis what would the new point be"?,"if the previous point was rotated90 degrees clockwise what is the new point"?,"if the previous point was rotated270 degrees clockwise what is the new point"?,"if the previous point was reflected across the y axis what would the new point be"?,"if the previous point was translated7 units to the left and9 units up what would the new point be"?,"if the previous point was translated5 units right and units15down what is the new point"?
concatenated"if"+"77"+"percent"+"of"+"americans"+"view"+"biohacked"+"as"+"a"+"good"+"book"+"for"+"covid"+"international"+"relations"+"what"+"percent"+"dont"?]
covid strings26 scrambled phrase list=["noztic"+"rivseus","ovicd"+"acvine"+"hesding"]
covid strings26 bonus question1=("if"+"the"+"slope"+"of"+"the"+"covid-lockdowns"+"line"+"was"+"increased"+"to"+"1"+"given"+"the"+"same"+"y"+"intercept"+"what"+"is"+"the"+"new"+"y"+"point"?)
userin.select team
import meta.
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
x1=0
y1=2
x2=7
y2=x2*1/2+2
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings  type=linear slope>=1
transformationlist=[reflection,rotation,translation]
if reflection(7,5.5)==x axis:
sign.change y coordinate
else:
remain
if rotation(7,-5.5)==90 degrees clockwise:
shift 90 degrees clockwise 
else:
remain
if rotation(-7,-5.5)==270 degrees clockwise
shift 270 degrees clockwise
else:
remain
if translation==(-7,9):
shift 7 units left and 9 units up 
else:
remain
if translation=(5,-15)
shift 5 units right and 15 units down
if selectedanswer==correct:
return true
else:
return false
if selectedanswer=not correct:
return false
else:
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
if users team wins covid strings26 
console log users team wins covid strings26
else
return game over
return filename
